---
title: "Exam 1:topics"
author: "Jaime Davila"
date: "3/17/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Topics

The following is a list of the topics that will be covered in the exam:

* Data types in R
* `tidyverse`: Including plots with `ggplot`, data transformation of tibbles with `dplyr` (including joins) and pivots
* Introduction to Prediction and Classification, including testing/training, MSE, missclassification rate, KNN models, class predicted probability and Bayes' boundary 
* Linear Models: Simple interpretation of coeffients in linear models and simple variable transformation. Use of the `tidymodels()` framework for running and evaluating models
* Classification: Logistic regression, multiple class classification including LDA, QDA and KNN models. Implementation and evaluation of classification models using `tidymodels`
* Cross validation: Definition and use of $k$-folds cross validation in the context of `tidymodels`






